### ISSUE TITLE
Investigate possibility to use IBM JDK on Travis

### ISSUE THREAD

**Issue by rsvoboda** [jboss-eap-qe/vdx-wildfly-testsuite#6]

**Comment by rsvoboda** [comment]
https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs
Travis CI provides OpenJDK 6, OpenJDK 7, Oracle JDK 7, and Oracle JDK 8

Looking at https://github.com/travis-ci/travis-ci/issues/2682 now

**Comment by rsvoboda** [comment]
Workaround is to pull docker image and run tests in docker ...

https://github.com/headius/invokebinder/commit/bce738d8236e720a6904a0fbd247f6d80154fcde

@mnovak1 I think it's not worth to spend more time on exploring options for IBM JDK. WDYT ?

**Comment by ameyjadiye** [comment]
@rsvoboda I have tried using docker for IBM sdk 8 it can run your application however we noticed that though mvn failed docker doesn't return -1 to its calling process hence travis report build as OK which is false.
