### ISSUE TITLE
Update pom.xml to use WF12 once it's released 

### ISSUE THREAD

**Issue by mnovak** [jboss-eap-qe/vdx-wildfly-testsuite#75]
This requires to update value of "version.org.jboss.wildfly.dist" property in pom.xml.

**Comment by mnovak** [comment]
This will fix failing test: MessagingTestCase.testWrongOrderOfElements which is currently failing with WF11 due to older xsd schema version for messaging-activemq subsystem.

**Comment by mnovak** [comment]
I've found WF12 Beta artifact:
        <dependency>
            <groupId>org.wildfly</groupId>
            <artifactId>wildfly-dist</artifactId>
            <version>12.0.0.Beta1</version>
        </dependency>

but it still contains old (2.0) schema for messaging-activemq subsystem. Version 3.0 is latest.

**Comment by rsvoboda** [comment]
CR1 was created yesterday, but I would wait for .Final. It's a matter of days.
